/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetTasks200Response,
  GetUsers200Response,
  GetUsers200ResponseItemsInner,
  ScanEvent200Response,
  ScanEventParams,
  VoteUserParams,
} from '../models/index';
import {
    GetTasks200ResponseFromJSON,
    GetTasks200ResponseToJSON,
    GetUsers200ResponseFromJSON,
    GetUsers200ResponseToJSON,
    GetUsers200ResponseItemsInnerFromJSON,
    GetUsers200ResponseItemsInnerToJSON,
    ScanEvent200ResponseFromJSON,
    ScanEvent200ResponseToJSON,
    ScanEventParamsFromJSON,
    ScanEventParamsToJSON,
    VoteUserParamsFromJSON,
    VoteUserParamsToJSON,
} from '../models/index';

export interface GetUserRequest {
    userId: number;
}

export interface GetUsersRequest {
    page?: number;
    pageSize?: number;
    sort?: string;
    sortField?: string;
    filerField?: string;
    filerOperator?: string;
    filerValue?: string;
    nameSearch?: string;
    citySearch?: string;
    genderSearch?: string;
    voteSearch?: number;
    ageFrom?: number;
    ageTo?: number;
}

export interface ScanEventRequest {
    scanEventParams: ScanEventParams;
}

export interface VoteUserRequest {
    userId: number;
    voteUserParams: VoteUserParams;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async getTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTasks200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTasks200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTasks200Response> {
        const response = await this.getTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsers200ResponseItemsInner>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUsers200ResponseItemsInnerFromJSON(jsonValue));
    }

    /**
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsers200ResponseItemsInner> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsers200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['sortField'] != null) {
            queryParameters['sortField'] = requestParameters['sortField'];
        }

        if (requestParameters['filerField'] != null) {
            queryParameters['filerField'] = requestParameters['filerField'];
        }

        if (requestParameters['filerOperator'] != null) {
            queryParameters['filerOperator'] = requestParameters['filerOperator'];
        }

        if (requestParameters['filerValue'] != null) {
            queryParameters['filerValue'] = requestParameters['filerValue'];
        }

        if (requestParameters['nameSearch'] != null) {
            queryParameters['nameSearch'] = requestParameters['nameSearch'];
        }

        if (requestParameters['citySearch'] != null) {
            queryParameters['citySearch'] = requestParameters['citySearch'];
        }

        if (requestParameters['genderSearch'] != null) {
            queryParameters['genderSearch'] = requestParameters['genderSearch'];
        }

        if (requestParameters['voteSearch'] != null) {
            queryParameters['voteSearch'] = requestParameters['voteSearch'];
        }

        if (requestParameters['ageFrom'] != null) {
            queryParameters['ageFrom'] = requestParameters['ageFrom'];
        }

        if (requestParameters['ageTo'] != null) {
            queryParameters['ageTo'] = requestParameters['ageTo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUsers200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getUsers(requestParameters: GetUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsers200Response> {
        const response = await this.getUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async scanEventRaw(requestParameters: ScanEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScanEvent200Response>> {
        if (requestParameters['scanEventParams'] == null) {
            throw new runtime.RequiredError(
                'scanEventParams',
                'Required parameter "scanEventParams" was null or undefined when calling scanEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/scan-event`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScanEventParamsToJSON(requestParameters['scanEventParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScanEvent200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async scanEvent(requestParameters: ScanEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScanEvent200Response> {
        const response = await this.scanEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async voteUserRaw(requestParameters: VoteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUsers200ResponseItemsInner>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling voteUser().'
            );
        }

        if (requestParameters['voteUserParams'] == null) {
            throw new runtime.RequiredError(
                'voteUserParams',
                'Required parameter "voteUserParams" was null or undefined when calling voteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{userId}/vote`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VoteUserParamsToJSON(requestParameters['voteUserParams']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUsers200ResponseItemsInnerFromJSON(jsonValue));
    }

    /**
     */
    async voteUser(requestParameters: VoteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUsers200ResponseItemsInner> {
        const response = await this.voteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
