/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { GetUsers200Response } from '../models/index';
import {
  GetUsers200ResponseFromJSON,
  GetUsers200ResponseToJSON,
} from '../models/index';

export interface GetUsersRequest {
  page: number;
  pageSize: number;
  sort?: string;
  sortField?: string;
  filerField?: string;
  filerOperator?: string;
  filerValue?: string;
  nameSearch?: string;
  citySearch?: string;
  genderSearch?: string;
  ageFrom?: number;
  ageTo?: number;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   */
  async getUsersRaw(
    requestParameters: GetUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUsers200Response>> {
    if (requestParameters['page'] == null) {
      throw new runtime.RequiredError(
        'page',
        'Required parameter "page" was null or undefined when calling getUsers().',
      );
    }

    if (requestParameters['pageSize'] == null) {
      throw new runtime.RequiredError(
        'pageSize',
        'Required parameter "pageSize" was null or undefined when calling getUsers().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    if (requestParameters['sort'] != null) {
      queryParameters['sort'] = requestParameters['sort'];
    }

    if (requestParameters['sortField'] != null) {
      queryParameters['sortField'] = requestParameters['sortField'];
    }

    if (requestParameters['filerField'] != null) {
      queryParameters['filerField'] = requestParameters['filerField'];
    }

    if (requestParameters['filerOperator'] != null) {
      queryParameters['filerOperator'] = requestParameters['filerOperator'];
    }

    if (requestParameters['filerValue'] != null) {
      queryParameters['filerValue'] = requestParameters['filerValue'];
    }

    if (requestParameters['nameSearch'] != null) {
      queryParameters['nameSearch'] = requestParameters['nameSearch'];
    }

    if (requestParameters['citySearch'] != null) {
      queryParameters['citySearch'] = requestParameters['citySearch'];
    }

    if (requestParameters['genderSearch'] != null) {
      queryParameters['genderSearch'] = requestParameters['genderSearch'];
    }

    if (requestParameters['ageFrom'] != null) {
      queryParameters['ageFrom'] = requestParameters['ageFrom'];
    }

    if (requestParameters['ageTo'] != null) {
      queryParameters['ageTo'] = requestParameters['ageTo'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/users`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUsers200ResponseFromJSON(jsonValue),
    );
  }

  /**
   */
  async getUsers(
    requestParameters: GetUsersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUsers200Response> {
    const response = await this.getUsersRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
