/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTasks200ResponseItemsInner
 */
export interface GetTasks200ResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof GetTasks200ResponseItemsInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetTasks200ResponseItemsInner
     */
    id: number;
}

/**
 * Check if a given object implements the GetTasks200ResponseItemsInner interface.
 */
export function instanceOfGetTasks200ResponseItemsInner(value: object): value is GetTasks200ResponseItemsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetTasks200ResponseItemsInnerFromJSON(json: any): GetTasks200ResponseItemsInner {
    return GetTasks200ResponseItemsInnerFromJSONTyped(json, false);
}

export function GetTasks200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTasks200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function GetTasks200ResponseItemsInnerToJSON(json: any): GetTasks200ResponseItemsInner {
    return GetTasks200ResponseItemsInnerToJSONTyped(json, false);
}

export function GetTasks200ResponseItemsInnerToJSONTyped(value?: GetTasks200ResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
    };
}

