/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetTasks200ResponseItemsInner } from './GetTasks200ResponseItemsInner';
import {
    GetTasks200ResponseItemsInnerFromJSON,
    GetTasks200ResponseItemsInnerFromJSONTyped,
    GetTasks200ResponseItemsInnerToJSON,
    GetTasks200ResponseItemsInnerToJSONTyped,
} from './GetTasks200ResponseItemsInner';

/**
 * 
 * @export
 * @interface GetTasks200Response
 */
export interface GetTasks200Response {
    /**
     * 
     * @type {number}
     * @memberof GetTasks200Response
     */
    count: number;
    /**
     * 
     * @type {Array<GetTasks200ResponseItemsInner>}
     * @memberof GetTasks200Response
     */
    items: Array<GetTasks200ResponseItemsInner>;
}

/**
 * Check if a given object implements the GetTasks200Response interface.
 */
export function instanceOfGetTasks200Response(value: object): value is GetTasks200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetTasks200ResponseFromJSON(json: any): GetTasks200Response {
    return GetTasks200ResponseFromJSONTyped(json, false);
}

export function GetTasks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTasks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'items': ((json['items'] as Array<any>).map(GetTasks200ResponseItemsInnerFromJSON)),
    };
}

export function GetTasks200ResponseToJSON(json: any): GetTasks200Response {
    return GetTasks200ResponseToJSONTyped(json, false);
}

export function GetTasks200ResponseToJSONTyped(value?: GetTasks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'items': ((value['items'] as Array<any>).map(GetTasks200ResponseItemsInnerToJSON)),
    };
}

