/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetUsers200ResponseItemsInner
 */
export interface GetUsers200ResponseItemsInner {
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  avatarPicture: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  occupation: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  gender: string;
  /**
   *
   * @type {number}
   * @memberof GetUsers200ResponseItemsInner
   */
  age: number;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof GetUsers200ResponseItemsInner
   */
  localsId: string;
  /**
   *
   * @type {number}
   * @memberof GetUsers200ResponseItemsInner
   */
  id: number;
}

/**
 * Check if a given object implements the GetUsers200ResponseItemsInner interface.
 */
export function instanceOfGetUsers200ResponseItemsInner(
  value: object,
): value is GetUsers200ResponseItemsInner {
  if (!('avatarPicture' in value) || value['avatarPicture'] === undefined)
    return false;
  if (!('city' in value) || value['city'] === undefined) return false;
  if (!('country' in value) || value['country'] === undefined) return false;
  if (!('occupation' in value) || value['occupation'] === undefined)
    return false;
  if (!('description' in value) || value['description'] === undefined)
    return false;
  if (!('gender' in value) || value['gender'] === undefined) return false;
  if (!('age' in value) || value['age'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('lastName' in value) || value['lastName'] === undefined) return false;
  if (!('firstName' in value) || value['firstName'] === undefined) return false;
  if (!('localsId' in value) || value['localsId'] === undefined) return false;
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function GetUsers200ResponseItemsInnerFromJSON(
  json: any,
): GetUsers200ResponseItemsInner {
  return GetUsers200ResponseItemsInnerFromJSONTyped(json, false);
}

export function GetUsers200ResponseItemsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUsers200ResponseItemsInner {
  if (json == null) {
    return json;
  }
  return {
    avatarPicture: json['avatarPicture'],
    city: json['city'],
    country: json['country'],
    occupation: json['occupation'],
    description: json['description'],
    gender: json['gender'],
    age: json['age'],
    username: json['username'],
    lastName: json['lastName'],
    firstName: json['firstName'],
    localsId: json['localsId'],
    id: json['id'],
  };
}

export function GetUsers200ResponseItemsInnerToJSON(
  json: any,
): GetUsers200ResponseItemsInner {
  return GetUsers200ResponseItemsInnerToJSONTyped(json, false);
}

export function GetUsers200ResponseItemsInnerToJSONTyped(
  value?: GetUsers200ResponseItemsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    avatarPicture: value['avatarPicture'],
    city: value['city'],
    country: value['country'],
    occupation: value['occupation'],
    description: value['description'],
    gender: value['gender'],
    age: value['age'],
    username: value['username'],
    lastName: value['lastName'],
    firstName: value['firstName'],
    localsId: value['localsId'],
    id: value['id'],
  };
}
