/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUsers200ResponseUsersInner
 */
export interface GetUsers200ResponseUsersInner {
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    avatarPicture: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    occupation: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    gender: string;
    /**
     * 
     * @type {number}
     * @memberof GetUsers200ResponseUsersInner
     */
    age: number;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetUsers200ResponseUsersInner
     */
    localsId: string;
    /**
     * 
     * @type {number}
     * @memberof GetUsers200ResponseUsersInner
     */
    id: number;
}

/**
 * Check if a given object implements the GetUsers200ResponseUsersInner interface.
 */
export function instanceOfGetUsers200ResponseUsersInner(value: object): value is GetUsers200ResponseUsersInner {
    if (!('avatarPicture' in value) || value['avatarPicture'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('occupation' in value) || value['occupation'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('localsId' in value) || value['localsId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GetUsers200ResponseUsersInnerFromJSON(json: any): GetUsers200ResponseUsersInner {
    return GetUsers200ResponseUsersInnerFromJSONTyped(json, false);
}

export function GetUsers200ResponseUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsers200ResponseUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarPicture': json['avatarPicture'],
        'city': json['city'],
        'country': json['country'],
        'occupation': json['occupation'],
        'description': json['description'],
        'gender': json['gender'],
        'age': json['age'],
        'username': json['username'],
        'lastName': json['lastName'],
        'firstName': json['firstName'],
        'localsId': json['localsId'],
        'id': json['id'],
    };
}

export function GetUsers200ResponseUsersInnerToJSON(json: any): GetUsers200ResponseUsersInner {
    return GetUsers200ResponseUsersInnerToJSONTyped(json, false);
}

export function GetUsers200ResponseUsersInnerToJSONTyped(value?: GetUsers200ResponseUsersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatarPicture': value['avatarPicture'],
        'city': value['city'],
        'country': value['country'],
        'occupation': value['occupation'],
        'description': value['description'],
        'gender': value['gender'],
        'age': value['age'],
        'username': value['username'],
        'lastName': value['lastName'],
        'firstName': value['firstName'],
        'localsId': value['localsId'],
        'id': value['id'],
    };
}

