/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsers200ResponseUsersInner } from './GetUsers200ResponseUsersInner';
import {
    GetUsers200ResponseUsersInnerFromJSON,
    GetUsers200ResponseUsersInnerFromJSONTyped,
    GetUsers200ResponseUsersInnerToJSON,
    GetUsers200ResponseUsersInnerToJSONTyped,
} from './GetUsers200ResponseUsersInner';

/**
 * 
 * @export
 * @interface GetUsers200Response
 */
export interface GetUsers200Response {
    /**
     * 
     * @type {Array<GetUsers200ResponseUsersInner>}
     * @memberof GetUsers200Response
     */
    users: Array<GetUsers200ResponseUsersInner>;
}

/**
 * Check if a given object implements the GetUsers200Response interface.
 */
export function instanceOfGetUsers200Response(value: object): value is GetUsers200Response {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function GetUsers200ResponseFromJSON(json: any): GetUsers200Response {
    return GetUsers200ResponseFromJSONTyped(json, false);
}

export function GetUsers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(GetUsers200ResponseUsersInnerFromJSON)),
    };
}

export function GetUsers200ResponseToJSON(json: any): GetUsers200Response {
    return GetUsers200ResponseToJSONTyped(json, false);
}

export function GetUsers200ResponseToJSONTyped(value?: GetUsers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(GetUsers200ResponseUsersInnerToJSON)),
    };
}

