/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsers200ResponseItemsInner } from './GetUsers200ResponseItemsInner';
import {
  GetUsers200ResponseItemsInnerFromJSON,
  GetUsers200ResponseItemsInnerFromJSONTyped,
  GetUsers200ResponseItemsInnerToJSON,
  GetUsers200ResponseItemsInnerToJSONTyped,
} from './GetUsers200ResponseItemsInner';

/**
 *
 * @export
 * @interface GetUsers200Response
 */
export interface GetUsers200Response {
  /**
   *
   * @type {number}
   * @memberof GetUsers200Response
   */
  count: number;
  /**
   *
   * @type {Array<GetUsers200ResponseItemsInner>}
   * @memberof GetUsers200Response
   */
  items: Array<GetUsers200ResponseItemsInner>;
}

/**
 * Check if a given object implements the GetUsers200Response interface.
 */
export function instanceOfGetUsers200Response(
  value: object,
): value is GetUsers200Response {
  if (!('count' in value) || value['count'] === undefined) return false;
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function GetUsers200ResponseFromJSON(json: any): GetUsers200Response {
  return GetUsers200ResponseFromJSONTyped(json, false);
}

export function GetUsers200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUsers200Response {
  if (json == null) {
    return json;
  }
  return {
    count: json['count'],
    items: (json['items'] as Array<any>).map(
      GetUsers200ResponseItemsInnerFromJSON,
    ),
  };
}

export function GetUsers200ResponseToJSON(json: any): GetUsers200Response {
  return GetUsers200ResponseToJSONTyped(json, false);
}

export function GetUsers200ResponseToJSONTyped(
  value?: GetUsers200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value['count'],
    items: (value['items'] as Array<any>).map(
      GetUsers200ResponseItemsInnerToJSON,
    ),
  };
}
