/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * From https://github.com/sindresorhus/type-fest/
 * Matches any valid JSON value.
 * @export
 * @interface JsonValue
 */
export interface JsonValue {
}

/**
 * Check if a given object implements the JsonValue interface.
 */
export function instanceOfJsonValue(value: object): value is JsonValue {
    return true;
}

export function JsonValueFromJSON(json: any): JsonValue {
    return JsonValueFromJSONTyped(json, false);
}

export function JsonValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonValue {
    return json;
}

export function JsonValueToJSON(json: any): JsonValue {
    return JsonValueToJSONTyped(json, false);
}

export function JsonValueToJSONTyped(value?: JsonValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

