/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanEvent200Response
 */
export interface ScanEvent200Response {
    /**
     * 
     * @type {number}
     * @memberof ScanEvent200Response
     */
    scanned: number;
}

/**
 * Check if a given object implements the ScanEvent200Response interface.
 */
export function instanceOfScanEvent200Response(value: object): value is ScanEvent200Response {
    if (!('scanned' in value) || value['scanned'] === undefined) return false;
    return true;
}

export function ScanEvent200ResponseFromJSON(json: any): ScanEvent200Response {
    return ScanEvent200ResponseFromJSONTyped(json, false);
}

export function ScanEvent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanEvent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scanned': json['scanned'],
    };
}

export function ScanEvent200ResponseToJSON(json: any): ScanEvent200Response {
    return ScanEvent200ResponseToJSONTyped(json, false);
}

export function ScanEvent200ResponseToJSONTyped(value?: ScanEvent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scanned': value['scanned'],
    };
}

