/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanEventParams
 */
export interface ScanEventParams {
    /**
     * 
     * @type {string}
     * @memberof ScanEventParams
     */
    id: string;
}

/**
 * Check if a given object implements the ScanEventParams interface.
 */
export function instanceOfScanEventParams(value: object): value is ScanEventParams {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ScanEventParamsFromJSON(json: any): ScanEventParams {
    return ScanEventParamsFromJSONTyped(json, false);
}

export function ScanEventParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanEventParams {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ScanEventParamsToJSON(json: any): ScanEventParams {
    return ScanEventParamsToJSONTyped(json, false);
}

export function ScanEventParamsToJSONTyped(value?: ScanEventParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

