/* tslint:disable */
/* eslint-disable */
/**
 * Locals Scrapper API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoteUserParams
 */
export interface VoteUserParams {
    /**
     * 
     * @type {number}
     * @memberof VoteUserParams
     */
    vote: number;
}

/**
 * Check if a given object implements the VoteUserParams interface.
 */
export function instanceOfVoteUserParams(value: object): value is VoteUserParams {
    if (!('vote' in value) || value['vote'] === undefined) return false;
    return true;
}

export function VoteUserParamsFromJSON(json: any): VoteUserParams {
    return VoteUserParamsFromJSONTyped(json, false);
}

export function VoteUserParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteUserParams {
    if (json == null) {
        return json;
    }
    return {
        
        'vote': json['vote'],
    };
}

export function VoteUserParamsToJSON(json: any): VoteUserParams {
    return VoteUserParamsToJSONTyped(json, false);
}

export function VoteUserParamsToJSONTyped(value?: VoteUserParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vote': value['vote'],
    };
}

